apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o9xurk4i6-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:9ce544b413cf9caa503b088d59289f67d6f3b243@sha256:e377389cf6c5d22f507a39a7b03b37d8da60d1f934a7b41ee9ee02a18a263950
          name: container-image
